// <auto-generated />
using System;
using CNX.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace APIs.Migrations.CNX
{
    [DbContext(typeof(CNXApplicationDbContext))]
    partial class CNXApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CNX.Data.Entities.CNXTalkpush", b =>
                {
                    b.Property<string>("CandidateId")
                        .HasColumnType("text");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("text");

                    b.Property<string>("CampaignTitle")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Education")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("ExtractedPagIbigNumber")
                        .HasColumnType("text");

                    b.Property<string>("ExtractedPhilhealthNumber")
                        .HasColumnType("text");

                    b.Property<string>("ExtractedSssNumber")
                        .HasColumnType("text");

                    b.Property<string>("ExtractedTinNumber")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JobRequisitionId")
                        .HasColumnType("text");

                    b.Property<string>("JobRequisitionPrimaryLocation")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<string>("Msa")
                        .HasColumnType("text");

                    b.Property<string>("PackageAccountName")
                        .HasColumnType("text");

                    b.Property<string>("PagIbigNumber")
                        .HasColumnType("text");

                    b.Property<string>("PhilhealthNumber")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<string>("SchoolName")
                        .HasColumnType("text");

                    b.Property<string>("SssNumber")
                        .HasColumnType("text");

                    b.Property<string>("TinNumber")
                        .HasColumnType("text");

                    b.Property<string>("UserPhoneNumber")
                        .HasColumnType("text");

                    b.HasKey("CandidateId");

                    b.ToTable("CNXTalkpushes");
                });
#pragma warning restore 612, 618
        }
    }
}
