namespace PhilSys.DTO;

public record PartnerSystemResponseDTO(
	string code,
	string token,
	string reference,
	string face_url,
	string full_name,
	string first_name,
	string middle_name,
	string last_name,
	string? suffix,
	string gender,
	string marital_status,
	string blood_type,
	string email,
	string mobile_number,
	string birth_date,
	string full_address,
	string address_line_1,
	string? address_line_2,
	string barangay,
	string municipality,
	string province,
	string country,
	string postal_code,
	string present_full_address,
	string present_address_line_1,
	string? present_address_line_2,
	string present_barangay,
	string present_municipality,
	string present_province,
	string present_country,
	string present_postal_code,
	string residency_status,
	string place_of_birth,
	string pob_municipality,
	string pob_province,
	string pob_country
);


